---
abstract: 'A pure-perl implementation of zabbix-sender.'
author:
  - 'Dominik Schulz <dominik.schulz@gauner.org>'
build_requires:
  English: 0
  File::Spec: 0
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Zabbix-Sender
requires:
  IO::Select: 0
  IO::Socket: 0
  JSON: 0
  Moose: 0
  Net::Domain: 0
  bytes: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/gittex/Zabbix-Sender/issues
  repository: git://github.com/gittex/Zabbix-Sender.git
version: 0.03
